# Database Development Environment Configuration

app:
  name: database
  replicas: 1

email: raskeb-1@student.ltu.se

environment: Development
message: "Database - Development Environment"

image:
  repository: postgres
  tag: "16"

storage:
  size: 1Gi
  
StorageClassName: local-path 
Timezone: "Europe/Stockholm"

DBUser: "postgres"
DBPassword: "group7password"
DBName: "mydatabase"
DBImage: postgres:16
DBResourceLimit: true
DBCPU: "2000m"
DBMemory: "1000Mi"
DBStorage: 10Gi

