app:
  name: backend
  replicas: 1

domain: backend.ltu-m7011e-7.se
email: raskeb-1@student.ltu.se

message: "Hello from Kubernetes with SSL!"

image:
  repository: ghcr.io/k4ffeman/backend
  tag: latest


database:
  host: postgres-service.database-dev.svc.cluster.local  # Same namespace - simplified
  port: 5432
  name: mydatabase
  username: postgres
  password: group7password
ingress:
  certIssuer: letsencrypt-staging

redeployAt: "2026-01-05 12:50:00"
