app:
  name: backend
  replicas: 3

domain: backend.ltu-m7011e-7.se
email: raskeb-1@student.ltu.se

message: "Hello from Kubernetes with SSL!"

image:
  repository: ghcr.io/k4ffeman/backend
  tag: latest


database:
  host: postgres-service.database-dev.svc.cluster.local  # Same namespace - simplified
  port: 5432
  name: mydatabase
  username: postgres
  password: group7password
ingress:
  certIssuer: letsencrypt-staging

amqp:
  url: amqp://admin:adminpass@rabbitmq-service-api.rabbitmq-dev.svc.cluster.local:5672

redeployAt: "2026-01-25 19:31:00"
