app:
  name: backend
  replicas: 1

domain: backend.ltu-m7011e-7.se
email: raskeb-1@student.ltu.se

message: "Hello from Kubernetes with SSL!"

image:
  repository: ghcr.io/K4ffeMan/m7011e/tree/main/backend
  tag: latest

ingress:
  certIssuer: letsencrypt-staging
