apiVersion: v1
kind: Secret
metadata:
  name: video-service-secret
type: Opaque
stringData:
  host: {{.Values.database.host}}
  port: "{{.Values.database.port}}"
  name: {{.Values.database.name}}
  username: {{ .Values.database.username }}
  password: {{ .Values.database.password }}
  rabbitmq: {{ .Values.amqp.url }}