app:
  name: frontend
  replicas: 1

domain: frontend-dev.ltu-m7011e-7.se
email: raskeb-1@student.ltu.se
environment: Development
message: "Frontend Dev Environment"

image:
  repository: ghcr.io/k4ffeman/frontend
  tag: latest

ingress:
  certIssuer: letsencrypt-prod

redeployAt: "2026-01-26 10:41:00"