app:
  name: frontend
  replicas: 1

domain: frontend-dev.ltu-m7011e-7.se
email: raskeb-1@student.ltu.se
environment: Development
message: "Frontend Dev Environment"

image:
  repository: ghcr.io/K4ffeMan/frontend
  tag: latest

ingress:
  certIssuer: letsencrypt-staging
