app:
  name: frontend
  replicas: 1

domain: frontend-dev.ltu-m7011e-7.se
email: raskeb-1@student.ltu.se
environment: Development
message: "Frontend Dev Environment"

image:
  repository: ghcr.io/k4ffeman/frontend
  tag: latest

ingress:
  certIssuer: letsencrypt-staging

api:
  url: http://backend.backend-dev.svc.cluster.local/

redeployAt: "2026-01-05 13:48:00"