apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Kebertr/m7011e-gitops.git
    targetRevision: main
    path: k8s/keycloak
    helm:
      valueFiles:
        - ../environments/keycloak/dev/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
