# Frontend Production Environment Configuration

app:
  name: frontend
  replicas: 3

domain: frontend.ltu-m7011e-7.se
email: raskeb-1@student.ltu.se

environment: Production
message: "Frontend - Production Environment"

image:
  repository: ghcr.io/k4ffeman/frontend
  tag: latest

ingress:
  certIssuer: letsencrypt-prod
